<h2 class = "header">Миний хичээлүүд</h2>
<hr/>

<?php
foreach ($this -> list as $value) { ?>
	<div class="row">
      <div class="col-xs-12">
        <h3><a class = "subheader" href="<?php echo $this -> baseUrl()?>/student/topics/id/<?php echo $value['id'] ?>"><?php echo $value['name']; ?></a></h3>
        <p><?php echo $value['description']; ?></p>
        <div class = "col-md-12 myrow" style="height: 25px;">
	        <ul class="list-inline pull-right">
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Даалгаварууд" href="<?php echo $this -> baseUrl() ?>/student/tasks/id/<?php echo $value['id'] ?>"><i class="glyphicon glyphicon-tasks"></i> </a></li>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Сэдвүүд" href="<?php echo $this -> baseUrl() ?>/student/lists/id/<?php echo $value['id'] ?>"><i class="glyphicon glyphicon-share-alt"></i> </a></li>
	        </ul>
        </div>
      </div>
    </div>
    <hr>
	<?php
}
?>
