<h4><?php if ($this -> thefor == 'code') echo 'Идэвхижүүлэх код авах' ; else echo 'Нэвтрэх' ?></h4>
<hr/>
<?php
if ($this -> thefor == 'new') {
	echo '<div class="alert alert-success alert-dismissable">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		  <strong>Баяр хүргэе.</strong> Таны нүүц үг амжилттай сэргээгдлээ. Та шинэ нууц үгээрээ нэвтэрнэ үү.</div>';
}
echo $this -> errors;
echo $this -> form;
