<script>
$(document).ready(function() {
	var body = $(".form-body").html();
	var body = '<div class = "form-header"><strong><?php echo $this -> form -> title; ?></strong></div><?php echo $this -> errors; ?>' + body;
	$(".form-body").html(body);
	
	$("#schools").live('change', function() {
		$.ajax({
            type: 'POST',
            dataType: 'json',
            url: baseUrl+'/ajax/faculty',
            async: false,
            data: { id: $(this).val() },
            success: function(res) {
                $("#faculty").html("");
                $.each(res, function(i, val){
   					$("#faculty").append('<option value="'+ val.id +'">'+ val.name +'</option>');
    			});
            }
    	});
	});
});
</script>

<?php

echo $this -> form;