<h2 class = "header"><?php echo $this -> name; ?></h2>
<span>
<?php
if ($this -> val == 0)
	echo 'Судлах хүсэлт илгээсэн оюутнууд';
else if ($this -> val == 1)
	echo 'Судлаж буй оюутнууд';
else
	echo 'Судлах хүсэлт нь цуцлагдсан оюутнууд';
?>
</span>
<hr/>
<div class = "col-xs-12">
	<span class = "pull-right">
		Бүгдийг (
		<?php if ($this -> val == 0 || $this -> val == 2) {
			echo '<a class = "label label-primary" href = "javascript:acceptAll('. $this -> id .')" class = ""><i class = "glyphicon glyphicon-ok"> Зөвшөөрөх</i></a> ';
		} else {
			echo '<a class = "label label-default" href = "javascript:cancelAll('. $this -> id .')" class = ""><i class = "glyphicon glyphicon-remove"></i> Цуцлах</a> ';
		} ?>
		
		<?php if ($this -> val == 0) {
			echo '<a class = "label label-default" href = "javascript:cancelAll('. $this -> id .')" class = ""><i class = "glyphicon glyphicon-remove"> Цуцлах</i></a> ';
		} else {
			echo '<a class = "label label-danger" href = "javascript:removeAll('. $this -> id .')" class = ""><i class = "glyphicon glyphicon-trash"></i> Устгах</a> ';
		} ?>
		)
	</span>
</div>

<table class = "table table-striped table-condensed">
	<thead>
		<tr>
			<th>#</th>
			<th style="width: 70%">Овог нэр</th>
			<th colspan="2"></th>
		</tr>
	</thead>
	<tbody>
		<?php
		$i = 1;
		foreach ($this -> list as $key => $value) {
			echo '<tr id = "'.$value['id'].'"><td>' . $i++ . '</td>';
			echo '<td><a href = "'.$this -> baseUrl().'/users/profile/id/'.$value['uid'].'">' . mb_substr($value['lname'], 0, 1, 'utf8') . '. ' . $value['fname'] . '</a></td>';
			if ($this -> val == 0 || $this -> val == 2)
				echo '<td><a  class = "label label-primary"  href="javascript:accept('.$value['id'].')"><i class = "glyphicon glyphicon-ok"></i> Зөвшөөрөх</a></td>';
			else if ($this -> val == 1)
				echo '<td><a  class = "label label-default"  href="javascript:cancel('.$value['id'].')"><i class = "glyphicon glyphicon-remove"></i> Цуцлах</a></td>';
			if ($this -> val == 0)
				echo '<td><a class = "label label-default" href="javascript:cancel('.$value['id'].')"><i class = "glyphicon glyphicon-remove"></i> Цуцлах</a></td>';
			else
				echo '<td><a class = "label label-danger" href="javascript:remove('.$value['id'].')"><i class = "glyphicon glyphicon-trash"></i> Устгах</a></td>';
				 
			echo '</tr>';
		} 
		?>
	</tbody>
</table>

<div class = "col-xs-12" id = "ftcon">
	
</div>

<script>

var lid = <?php echo $this -> id;?>;

function get() {
	$.ajax({
		type: "POST",
		url: baseUrl + "/lesson/get/id/" + lid,
		data: "format = json",
		async: false,
		success: function(res) {
			res = JSON.parse(res);
			content = "";
			content += '<ul class="list-inline pull-left">';
        	content += '<span style = "color: #2a6496">Оюутнууд: </span>';
        	content += '<li><a class = "tt" data-toggle="tooltip" data-original-title="Судлах хүсэлт" href="'+baseUrl+'/lesson/students/id/'+lid+'/val/0">';
        	content += '<i class="glyphicon glyphicon-globe"></i> ' + res.a;
        	content += '</a></li><li>';
        	content += '<a class = "tt" data-toggle="tooltip" data-original-title="Судалж байгаа" href="'+baseUrl+'/lesson/students/id/'+lid+'/val/1">';
        	content += '<i class="glyphicon glyphicon-ok"></i> ' +  res.b;
        	content += '</a></li><li>';
        	content += '<a class = "tt" data-toggle="tooltip" data-original-title="Цуцалсан" href="'+baseUrl+'/lesson/students/id/'+lid+'/val/2">';
        	content += '<i class="glyphicon glyphicon-remove"></i> ' + res.c;
        	content += '</a></li></ul>';
        	$("#ftcon").html(content);
		},
		error: function() {
			alert("Уучлаарай ямар нэг алдаа гарлаа.");
		}
	});
}

function sendRequest(id, url, val) {
	if (val == 0) {
		$.ajax({
			type: "POST",
			url: url,
			data: "format = json",
			async: false,
			success: function(res){
				if (val == 1) {
					get();
				} else {
					
					window.location.replace(baseUrl + '/lesson/list');
				}
			},
			error: function() {
				alert("Уучлаарай ямар нэг алдаа гарлаа.");
			}
		});
	} else {
		$("#" + id).hide("slow", function() {
			$.ajax({
				type: "POST",
				url: url,
				data: "format = json",
				async: false,
				success: function(res){
					if (val == 1) {
						get();
					} else {
						
						window.location.replace(baseUrl + '/lesson/list');
					}
				},
				error: function() {
					alert("Уучлаарай ямар нэг алдаа гарлаа.");
				}
			});
		});
	}
}

function remove(id) {
	var url = baseUrl + "/lesson/save/val/1/q/0/id/"+id;
	sendRequest(id, url, 1);
}

function accept(id) {
	var url = baseUrl + "/lesson/save/val/1/q/1/id/"+id;
	sendRequest(id, url, 1);
}

function cancel(id) {
	var url = baseUrl + "/lesson/save/val/1/q/2/id/"+id;
	sendRequest(id, url, 1);
}

function removeAll(id) {
	var url = baseUrl + "/lesson/save/val/0/q/0/old/<?php echo $this -> val ?>/id/"+id;
	sendRequest(id, url, 0);
}

function acceptAll(id) {
	var url = baseUrl + "/lesson/save/val/0/q/1/old/<?php echo $this -> val ?>/id/"+id;
	sendRequest(id, url, 0);
}

function cancelAll(id) {
	var url = baseUrl + "/lesson/save/val/0/q/2/old/<?php echo $this -> val ?>/id/"+id;
	sendRequest(id, url, 0);
}

$(document).ready(function() {
	get();
});

</script>
