<h2><?php echo $this -> name; ?></h2>
<span>
<?php
if ($this -> val == 0)
	echo 'Судлах хүсэлт илгээсэн оюутнууд';
else if ($this -> val == 1)
	echo 'Судлаж буй оюутнууд';
else
	echo 'Судлах хүсэлт нь цуцлагдсан оюутнууд';
?>
<span>
<hr/>

<table class = "table table-striped">
	<thead>
		<th>#</th>
		<th>Овог нэр</th>
		<th colspan="2"></th>
	</thead>
	<tbody>
		<?php
		foreach ($this -> list as $key => $value) {
			echo '<tr><td>' . substr_unicode($value -> lname, 0, 1) . $value -> fname . '<td>';
			echo '<td></td>';
			echo '<td></td></tr>';
		} 
		?>
	</tbody>
</table>
