<h2 class = "header"><?php echo $this -> name; ?></h2>
<hr/>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right" style="border-left:1px solid #E7E7E7">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class = "glyphicon glyphicon-wrench"></i></a>
          <ul class="dropdown-menu">
            <li><a href="javascript:add()"><i class = "glyphicon glyphicon-plus"></i> Хичээл нэмэх</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>



<?php
foreach ($this -> list as $key => $value) {
	$a = 0; $b = 0; $c = 0;
	if (isset($this -> req[$value -> id])) {
		$a = $this -> req[$value -> id][0];
		$b = $this -> req[$value -> id][1];
		$c = $this -> req[$value -> id][2];
	}
	?>
	<div class="row">
      <div class="col-xs-12">
        <h3><?php echo $value -> name; ?></h3>
        <p><?php echo $value -> description; ?></p>
        <div class = "col-md-12 myrow" style="height: 25px;">
	        <ul class="list-inline pull-right">
	        	<li><a class = "delete-link" href="<?php echo $this -> baseUrl() ?>/lesson/delete/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-trash"></i> Устгах</a></li>
	        	<li><a href="<?php echo $this -> baseUrl() ?>/lesson/edit/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-edit"></i> Засварлах</a></li>
	        	<li><a href="<?php echo $this -> baseUrl() ?>/task/list/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-tasks"></i> Даалгаварууд</a></li>
	        	<li><a href="<?php echo $this -> baseUrl() ?>/lesson/view/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-share-alt"></i> Дэлгэрэнгүй</a></li>
	        </ul>
	        
	        <ul class="list-inline pull-left">
	        	<span style = "color: #2a6496">Оюутнууд: </span>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Судлах хүсэлт" href="<?php echo $this -> baseUrl() ?>/lesson/students/id/<?php echo $value -> id ?>/val/0">
	        			<i class="glyphicon glyphicon-globe"></i> <?php echo $a ?>
	        		</a>
	        	</li>
	        	<li>
	        		<a class = "tt" data-toggle="tooltip" data-original-title="Судалж байгаа" href="<?php echo $this -> baseUrl() ?>/lesson/students/id/<?php echo $value -> id ?>/val/1">
	        			<i class="glyphicon glyphicon-ok"></i> <?php echo $b ?>
	        		</a>
	        	</li>
	        	<li>
	        		<a class = "tt" data-toggle="tooltip" data-original-title="Цуцалсан" href="<?php echo $this -> baseUrl() ?>/lesson/students/id/<?php echo $value -> id ?>/val/2">
	        			<i class="glyphicon glyphicon-remove"></i> <?php echo $c ?>
	        		</a>
	        	</li>
	        </ul>
        </div>
      </div>
    </div>
    <hr>
	<?php
}
?>

<div class="modal fade bs-example-modal-lg" id = "lesson-add" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Хичээл нэмэх</h4>
      </div>
      <div class="modal-body">
        <form enctype="application/x-www-form-urlencoded" method="post" action="/lesson/lesson/add">
        <dt id="name-label"><label for="name" class="required">Хичээлийн нэр:</label></dt>
<dd id="name-element">
<input type="text" name="name" id="name" value="" class="form-control"></dd>
<dt id="description-label"><label for="description" class="optional">Хичээлийн тодорхойлолт:</label></dt>
<dd id="description-element">
<textarea name="description" id="description" class="form-control summernote-small" rows="24" cols="80"></textarea></dd>
</dd>

      </div>
      <div class="modal-footer">
<input type="submit" name="submit" id="submit" value="Хадгалах" class="btn btn-default btn-primary">
      </div>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript">
    function add() {
        $("#lesson-add").modal('show');
        $("#name").focus();
    }
	
	$('.delete-link').mouseenter(function() {
		if ($(this).hasClass('done')) {
		} else if ($(this).hasClass('click-me')) {
			$(this).addClass('done');
			$(this).removeClass('click-me');
		} else {
			$(this).addClass('click-me');
		}
	});
	
	$('.myrow').mouseleave(function(event) {
		$('.delete-link').removeClass('click-me');
		$('.delete-link').removeClass('done');
	});
</script>