<style type="text/css">
	.z-clip-wrap{
		position: relative;
		display : inline-block;
	}
</style>

<h2 class = "header">Файлын жагсаалт</h2>
<hr/>
<table class="table table-striped">
	<thead>
		<tr>
			<th style="width:40px;">#</th>
			<th>Нэр</th>
			<th style="width:40px;"></th>
			<th style="width:40px;">URI</th>
			<th style="width:40px;"></th>
		</tr>
	</thead>
	<tbody>
		<?php
		$i = ($this -> page - 1) * 20;
		foreach ($this -> paginator as $file) { ?>
			<tr class = "myrow" id = "row<?php echo $file['id'] ?>">
				<td><?php echo ++$i; ?>.</td>
				<td><?php echo $file['name']; ?></td>
				<td><a class="label label-danger delete-link" id = "del<?php echo $file['id'] ?>" href="javascript:void(0)"><i class="glyphicon glyphicon-trash"></i> Устгах</a></td>
				<td>
					<span class="z-clip-wrap">
						<a class="label label-primary copy-button" id="<?php echo $file['uri'] ?>" href="javascript:void(0)">
							<i class="glyphicon glyphicon-log-out"></i> URI
						</a>
					</span>
				</td>
				<td><a class="label label-default" href="<?php echo $this -> baseUrl() ?>/file/download/id/<?php echo $file['id'] ?>"><i class="glyphicon glyphicon-download"></i> Татах</a></td>
			</tr>
		<?php } ?>
	</tbody>
</table>


<div class = "quick-message">Ачаалж байна...</div>

<hr/>
<script src="<?php echo $this -> baseUrl(); ?>/public/plugins/zclip/jquery.zclip.min.js"></script>

<script>

function delete1(id) {
	$(".quick-message").html('Ачаалж байна...');
	$(".quick-message").slideDown();
	$("#row" + id).addClass('danger');
	$.ajax({
        type: "POST",
        url: baseUrl + "/file/delete/id/" + id,
        cache: false,
        contentType: false,
        processData: false,
        success: function(res) {
        	$('.quick-message').hide();
        	$("#row" + id).removeClass('danger');
            $("#row" + id).hide('slow');
        },
        error: function() {
        	$('.quick-message').hide();
        }
    });
}

function visible(delid) {
	$("#del"+delid).addClass('label-danger');
	$("#del"+delid).removeClass('label-default');
}

$(document).ready(function() {
	$('.delete-link').mouseenter(function() {
		delid = $(this).attr('id').substr(3);
		if ($(this).hasClass('done')) {
		} else if ($(this).hasClass('click-me')) {
			$(this).addClass('done');
			$(this).removeClass('click-me');
		} else {
			$(this).addClass('click-me');
		}
	});

	$('.myrow').mouseleave(function(event) {
		id = $(this).attr('id');
		if (id != undefined) {
			id = id.substr(3);
			$('#del' + id).removeClass('click-me');
			$('#del' + id).removeClass('done');
		}
	});
	
	$('.delete-link').click(function() {
		id = $(this).attr('id');
		id = id.substr(3);
		delete1(id);
	});

	$('.quick-message').hide();
	$('.quick-message').removeClass('hide');

	function hide() {
		$( ".quick-message" ).hide();
	}

	$('.quick-message').click(function() {
		$(this).hide();
	});
	function copied() {
		if ($(".quick-message").is( ":hidden" )) {
			msg = '<h3>Холбоосыг хуулсан.</h3><p>Энд дарвал алга болно.</p>';
			$(".quick-message").html(msg);
		    $(".quick-message").slideDown();
		    setTimeout(hide, 3000);
		}
	}

	$(".copy-button").zclip({
        path: baseUrl + "/public/plugins/zclip/ZeroClipboard.swf",
        copy: function() { return baseUrl + $(this).attr('id'); },
        afterCopy:function(){
            copied();
        }
    });
});


</script>

