<h2 class = "header">Миний хичээлүүд</h2>
<hr/>

<div class="bs-example bs-example-tabs">
	<ul id="myTab" class="nav nav-tabs">
	  <li class="dropdown pull-right">
	  	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class = "fa fa-cogs"></i></a>
        <ul class="dropdown-menu">
            <li><a href="javascript:add()"><i class = "glyphicon glyphicon-plus"></i> Хичээл нэмэх</a></li>
        </ul>
	  </li>
	</ul>
</div>


<?php
foreach ($this -> list as $key => $value) {
	$a = 0; $b = 0; $c = 0;
	if (isset($this -> req[$value -> id])) {
		$a = $this -> req[$value -> id][0];
		$b = $this -> req[$value -> id][1];
		$c = $this -> req[$value -> id][2];
	}
	?>
	<div class="row">
      <div class="col-xs-12">
        <h3><a class = "subheader" href="<?php echo $this -> baseUrl()?>/topic/list/id/<?php echo $value -> id ?>"><?php echo $value -> name; ?></a></h3>
        <p><?php echo base64_decode($value -> description); ?></p>
        <div class = "col-md-12 myrow" style="height: 25px;">
	        <ul class="list-inline pull-right">
	        	<li><a class = "delete-link tt" data-toggle="tooltip" data-original-title="Устгах"  href="<?php echo $this -> baseUrl() ?>/lessons/delete/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-trash"></i> </a></li>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Засварлах" href="<?php echo $this -> baseUrl() ?>/lessons/edit/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-edit"></i> </a></li>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Даалгаварууд" href="<?php echo $this -> baseUrl() ?>/task/list/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-tasks"></i> </a></li>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Сэдвүүд" href="<?php echo $this -> baseUrl() ?>/topic/list/id/<?php echo $value -> id ?>"><i class="glyphicon glyphicon-share-alt"></i> </a></li>
	        </ul>
	        
	        <ul class="list-inline pull-left">
	        	<span style = "color: #2a6496">Оюутнууд: </span>
	        	<li><a class = "tt" data-toggle="tooltip" data-original-title="Судлах хүсэлт" href="<?php echo $this -> baseUrl() ?>/lessons/students/id/<?php echo $value -> id ?>/val/0">
	        			<i class="glyphicon glyphicon-globe"></i> <?php echo $a ?>
	        		</a>
	        	</li>
	        	<li>
	        		<a class = "tt" data-toggle="tooltip" data-original-title="Судалж байгаа" href="<?php echo $this -> baseUrl() ?>/lessons/students/id/<?php echo $value -> id ?>/val/1">
	        			<i class="glyphicon glyphicon-ok"></i> <?php echo $b ?>
	        		</a>
	        	</li>
	        	<li>
	        		<a class = "tt" data-toggle="tooltip" data-original-title="Цуцалсан" href="<?php echo $this -> baseUrl() ?>/lessons/students/id/<?php echo $value -> id ?>/val/2">
	        			<i class="glyphicon glyphicon-remove"></i> <?php echo $c ?>
	        		</a>
	        	</li>
	        </ul>
        </div>
      </div>
    </div>
    <hr>
	<?php
}
?>

<div class="modal fade bs-example-modal-lg" id = "lesson-add" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Хичээл нэмэх</h4>
      </div>
      <div class="modal-body">
        <form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this -> baseUrl(); ?>/lessons/add">
        <dt id="name-label"><label for="name" class="required">Хичээлийн нэр:</label></dt>
		<dd id="name-element">
		<input type="text" name="name" id="name" value="" class="form-control"></dd>
		<dt id="description-label"><label for="description" class="optional">Хичээлийн тодорхойлолт:</label></dt>
		<dd id="description-element">
		<textarea name="description" id="description" class="form-control summernote-small" rows="24" cols="80"></textarea></dd>
		</dd>
		<dt id="public-label"><label for="public" class="optional">Нээлттэй хичээл:</label></dt>
		<dd id="public-element">
		<select name="public" id="public" class="form-control">
		    <option value="0">Хаалттай хичээл: (Зөвхөн зөвшөөрсөн оюутнууд үзэх боломжтой)</option>
		    <option value="1">Нээлттэй хичээл: (Хүн бүхэн үзэх боломжтой)</option>
		</select></dd>
		
      </div>
      <div class="modal-footer">
<input type="submit" name="submit" id="submit" value="Хадгалах" class="btn btn-default btn-primary">
      </div>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript">
    function add() {
        $("#lesson-add").modal('show');
        $("#name").focus();
    }
	
	$('.delete-link').mouseenter(function() {
		if ($(this).hasClass('done')) {
		} else if ($(this).hasClass('click-me-small')) {
			$(this).addClass('done');
			$(this).removeClass('click-me-small');
		} else {
			$(this).addClass('click-me-small');
		}
	});
	
	$('.myrow').mouseleave(function(event) {
		$('.delete-link').removeClass('click-me-small');
		$('.delete-link').removeClass('done');
	});
</script>