<h2 class = "header">Багш нар</h2>
<hr/>
<?php
foreach ($this -> list as $key => $value) { ?>
	<div class="row">
      <div class="col-xs-12">
        <h3><?php echo mb_substr($value -> lname, 0, 1, 'utf8') . '. ' . $value -> fname; ?></h3>
        
        <p><?php echo mb_substr($value -> bio, 0, 100, 'utf8');
        		if (mb_substr($value -> bio, 0, 100, 'utf8') != mb_substr($value -> bio, 0, 99, 'utf8'))
        			echo '...'; ?></p>
        
        <ul class="list-inline pull-right">
        	<li><a href = "<?php echo $this -> baseUrl() ?>/teacher/lessons/id/<?php echo $value -> id; ?>"><i class="glyphicon glyphicon-indent-left"></i> Хичээлүүд</a></li>
        	<li><a href = "<?php echo $this -> baseUrl() ?>/users/profile/id/<?php echo $value -> id; ?>"><i class="glyphicon glyphicon-share-alt"></i> Дэлгэрэнгүй</a></li>
        </ul>
        
      </div>
    </div>
    <hr>
	<?php
}
?>