<?php $baseUrl = "http://localhost/lesson/public"; ?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Bootply.com - Portal Template</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="<?php echo $baseUrl ?>/dist/css/bootstrap.min.css" rel="stylesheet">
		
  		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
  		<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
  		
		<link href="<?php echo $baseUrl ?>/css/style.css" rel="stylesheet">
		<link href="<?php echo $baseUrl ?>/css/form-style.css" rel="stylesheet">
		<link href="<?php echo $baseUrl ?>/dist/summernote.css" rel="stylesheet">
		
		<!-- include codemirror (codemirror.css, codemirror.js, xml.js, formatting.js) -->
		<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
		<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.min.css" />
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
		
		<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<style type="text/css">
			body {
				padding-top: 70px;
				font-family: "Times new roman"
			}
			.wrap {
				margin-left: 0;
				margin-right: 0;
			}
		</style>
		
		<script type='text/javascript' src="<?php echo $baseUrl ?>/js/jquery.min.js"></script>
		<script type='text/javascript' src="<?php echo $baseUrl ?>/js/script.js"></script>
		<script>
			var baseUrl = "http://localhost/lesson";
		</script>
	</head>

	<!-- HTML code from Bootply.com editor -->

	<body>
		
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-6" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="#">Action</a>
					</li>
					<li>
						<a href="#">Another action</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">Separated link</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">One more separated link</a>
					</li>
				</ul>
			</li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
		
		

		<div class="row wrap">

			<!--left-->
			<div class="col-sm-3 left-content" id = "left-content">

				<div class="row">
					<div class="col-xs-12">
						<h2>Side</h2>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
								Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
								dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
					</div>
				</div>

			</div><!--/left-->

			<!--center-->
			<div class="col-sm-9 right-content" id = "right-content">

				<div class="row">
					<div class="col-xs-12">
						<?php echo $this -> layout() -> content; ?>
					</div>
				</div>
				<hr />
				

				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">4 Days Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 7 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 56 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">1 Week Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="latex1">
					<img src="http://latex.codecogs.com/gif.latex?a^{2} + b^{2}  \geq 2ab"> => <img src="http://latex.codecogs.com/gif.latex?\frac{a^{2} + b^{2}}{2}  \geq ab">
				</div>
				<hr>

			</div><!-- /.container -->

			<script type='text/javascript' src="<?php echo $baseUrl ?>/dist/js/bootstrap.min.js"></script>
			<script type='text/javascript' src="<?php echo $baseUrl ?>/js/latex.js"></script>
			<script type="text/javascript" src="<?php echo $baseUrl ?>/dist/summernote.min.js"></script>
			
			<!-- JavaScript jQuery code from Bootply.com editor -->
			<script type='text/javascript'>
				less = {
				    env: "development", // or "production"
				    async: false,       // load imports async
				    fileAsync: false,   // load imports async when in a page under
				    // a file protocol
				    poll: 1000,         // when in watch mode, time in ms between polls
				    functions: {},      // user functions, keyed by name
				    dumpLineNumbers: "comments", // or "mediaQuery" or "all"
				    relativeUrls: false,// whether to adjust url's to be relative
				    // if false, url's are already relative to the
				    // entry less file
				    rootpath: ":/a.com/"// a path to add on to the start of every url
				    //resource
				  };
				$(document).ready(function() {
					$(".tt").tooltip();
					$('.summernote-small').summernote({
					  /*toolbar: [
					    ['style', ['style']], // no style button
					    ['style', ['bold', 'italic', 'underline', 'clear']],
					    ['fontsize', ['fontsize']],
					    ['color', ['color']],
					    ['para', ['ul', 'ol', 'paragraph']],
					    ['height', ['height']],
					    //['insert', ['picture', 'link']], // no insert buttons
					    //['table', ['table']], // no table button
					    ['help', ['help']],
					    ['codeview', ['codeview']],
					    ['fullscreen', ['fullscreen']]
					  ],*/
					  onkeydown: function(e) {
					  	if (e.keyCode == 9) {
					  	  e.preventDefault();
					  	}
					  },
					  onImageUpload: function(files, editor, welEditable) {
		                sendFile(files[0], editor, welEditable);
			          }
					});
					
					function sendFile(file, editor, welEditable) {
			            data = new FormData();
			            data.append("file", file);
			            $.ajax({
			                data: data,
			                type: "POST",
			                url: baseUrl + "/file/upload/from/summernote",
			                cache: false,
			                contentType: false,
			                processData: false,
			                success: function(res) {
			                	res = JSON.parse(res);
			                    if (res.status == 1) {
			                    	editor.insertImage(welEditable, baseUrl + res.data);
			                    } else {
			                    	alert(res.data);
			                    }
			                }
			            });
			        }
				});
			</script>
			
			<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.3.3/less.min.js" type="text/javascript"></script>

	</body>
</html>