<?php

$baseUrl = $this -> serverUrl() . $this -> baseUrl()."/public";
$menu = new View_Helper_Menu($this -> baseUrl());

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Хичээлдээ</title>
	<link rel="shortcut icon" type="image/jpeg" href="<?php echo $baseUrl; ?>/images/favicon.jpg"/>
	<meta name="generator" content="Bootply" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link href="<?php echo $baseUrl ?>/dist/css/bootstrap.min.css" rel="stylesheet">
	
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
	
	<link href="<?php echo $baseUrl ?>/css/style.css" rel="stylesheet">
	<link href="<?php echo $baseUrl ?>/css/form-style.css" rel="stylesheet">
	<link href="<?php echo $baseUrl ?>/dist/summernote.css" rel="stylesheet">
	
	<!-- include codemirror (codemirror.css, codemirror.js, xml.js, formatting.js) -->
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" />
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.min.css" />
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.js"></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
	
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<style type="text/css">
		body {
			padding-top: 70px;
			font-family: "Times new roman"
		}
		.wrap {
			margin-left: 0;
			margin-right: 0;
		}
	</style>
	
	<script type='text/javascript' src="<?php echo $baseUrl ?>/js/jquery.min.js"></script>
	<script type='text/javascript' src="<?php echo $baseUrl ?>/js/script.js"></script>
	<script>
		var baseUrl = "<?php echo $this -> serverUrl() . $this -> baseUrl(); ?>";
	</script>
</head>

	<!-- HTML code from Bootply.com editor -->

<body>
		
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php if (Zend_Registry::get('role') == 'guests') {
          	echo '<a class="navbar-brand" href="'. $this -> baseUrl() .'/auth/login">Хичээлдээ</a>';
          } else {
          	echo '<a class="navbar-brand" href="'. $this -> baseUrl() .'/users/profile">Хичээлдээ</a>';
          } ?>
        </div>

        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-6" style="height: 1px;">
        	<ul class="nav navbar-nav">
        	<?php echo $menu -> getMenu(); ?>
			</ul>
			<?php if (Zend_Registry::get('role') != 'guests') { ?>
			<ul class="nav navbar-nav navbar-right" style="border-left:1px solid #E7E7E7">
		        <li class="dropdown">
		          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class = "fa fa-user"></i> <?php echo Zend_Registry::get('name'); ?> <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="<?php echo $this -> baseUrl(); ?>/users/manage/val/profile"><i class = "fa fa-smile-o"></i> Миний мэдээлэл</a></li>
		            <li><a href="<?php echo $this -> baseUrl(); ?>/users/manage/val/password"><i class="fa fa-key"></i> Нууц үгээ солих</a></li>
		            <li class="divider"></li>
		            <li><a href="<?php echo $this -> baseUrl(); ?>/auth/logout"><i class="fa fa-power-off"></i>  Гарах</a></li>
		          </ul>
		        </li>
      		</ul>
      		<?php } ?>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
		
		<div class="row wrap">

			<!--left-->
			<div class="col-sm-3 left-content" id = "left-content">

				<div class="row">
					<div class="col-xs-12">
						<h2>Side</h2>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
								Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
								dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
					</div>
				</div>

			</div><!--/left-->

			<!--center-->
			<div class="col-sm-9 right-content" id = "right-content">

				<div class="row">
					<div class="col-xs-12">
						<?php echo $this -> layout() -> content; echo $this -> serverUrl() . $this -> baseUrl(); ?>
					</div>
				</div>
				<hr />
				

				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">4 Days Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 7 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 56 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">1 Week Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="latex1">
					<img src="http://latex.codecogs.com/gif.latex?a^{2} + b^{2}  \geq 2ab"> => <img src="http://latex.codecogs.com/gif.latex?\frac{a^{2} + b^{2}}{2}  \geq ab">
				</div>
				<hr>

			</div><!-- /.container -->

			<script type='text/javascript' src="<?php echo $baseUrl ?>/dist/js/bootstrap.min.js"></script>
			<script type='text/javascript' src="<?php echo $baseUrl ?>/js/latex.js"></script>
			<script type="text/javascript" src="<?php echo $baseUrl ?>/dist/summernote.js"></script>
			
			<!-- JavaScript jQuery code from Bootply.com editor -->
			<script type='text/javascript'>
				function isImage(ext) {
					ext = ext.toLowerCase();
					return ext == 'jpg' || ext == 'png' || ext == 'gif';
				}
				$(document).ready(function() {
					$(".tt").tooltip();
					$('.summernote-small').summernote({
					  onkeydown: function(e) {
					  	if (e.keyCode == 9) {
					  	  e.preventDefault();
					  	}
					  },
					  onImageUpload: function(files, editor, welEditable) {
		                sendFile(files[0], editor, welEditable);
			          }
					});
					
					function sendFile(file, editor, welEditable) {
			            data = new FormData();
			            data.append("file", file);
			            filename = file.name;
			            extention = filename.split('.').pop();
			            if (isImage(extention)) {
				            $.ajax({
				                data: data,
				                type: "POST",
				                url: baseUrl + "/file/upload/from/summernote",
				                cache: false,
				                contentType: false,
				                processData: false,
				                success: function(res) {
				                	res = JSON.parse(res);
				                    if (res.status == 1) {
				                    	editor.insertImage(welEditable, baseUrl + res.data);
				                    } else {
				                    	alert(res.data);
				                    }
				                }
				            });
			        	} else {
			        		alert('Уучлаарай зугрийн формат буруу байна. (.jpg, .png, .gif)');
			        	}
			        }
				});
			</script>
			
			<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/1.3.3/less.min.js" type="text/javascript"></script>

	</body>
</html>