<?php $baseUrl = "http://localhost/lesson/public"; ?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Bootply.com - Portal Template</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="<?php echo $baseUrl ?>/dist/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?php echo $baseUrl ?>/css/style.css" rel="stylesheet">
		<link href="<?php echo $baseUrl ?>/css/form-style.css" rel="stylesheet">

		<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="/bootstrap/img/favicon.ico">
		<link rel="apple-touch-icon" href="/bootstrap/img/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/bootstrap/img/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/bootstrap/img/apple-touch-icon-114x114.png">

		<style type="text/css">
			body {
				padding-top: 70px;
				font-family: "Times new roman"
			}
			.wrap {
				margin-left: 0;
				margin-right: 0;
			}
		</style>

		<script type='text/javascript' src="<?php echo $baseUrl ?>/js/jquery.min.js"></script>
		<script type='text/javascript' src="<?php echo $baseUrl ?>/js/script.js"></script>
		<script>
			var baseUrl = "http://localhost/lesson";
		</script>
	</head>

	<!-- HTML code from Bootply.com editor -->

	<body>
		
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-6" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="#">Action</a>
					</li>
					<li>
						<a href="#">Another action</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">Separated link</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">One more separated link</a>
					</li>
				</ul>
			</li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
		
		

		<div class="row wrap">

			<!--left-->
			<div class="col-sm-3" id = "left-content">

				<div class="row">
					<div class="col-xs-12">
						<h2>Side</h2>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
								Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
								dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
								Aliquam in felis sit amet augue.
							</div>
						</div>
						<hr>
						<div class="panel panel-default">
							<div class="panel-heading">
								Title
							</div>
							<div class="panel-body">
								Content here..
							</div>
						</div>
						<hr>
					</div>
				</div>

			</div><!--/left-->

			<!--center-->
			<div class="col-sm-9" id = "right-content">

				<div class="row">
					<div class="col-xs-12">
						<?php echo $this -> layout() -> content; ?>
					</div>
				</div>
				<hr />
				<pre><code class="javascript"><span class="keyword">var</span> edit = <span class="keyword">function</span>() {
  $(<span class="string">'.click2edit'</span>).summernote();
};</code></pre>
				


				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">4 Days Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 7 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 56 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="row">
					<div class="col-xs-12">
						<h2>Article Heading</h2>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
							Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis
							dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan.
							Aliquam in felis sit amet augue.
						</p>
						<p class="lead">
							<button class="btn btn-default">
								Read More
							</button>
						</p>
						<p class="pull-right">
							<span class="label label-default">keyword</span><span class="label label-default">tag</span><span class="label label-default">post</span>
						</p>
						<ul class="list-inline">
							<li>
								<a href="#">1 Week Ago</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-comment"></i> 4 Comments</a>
							</li>
							<li>
								<a href="#"><i class="glyphicon glyphicon-share"></i> 34 Shares</a>
							</li>
						</ul>
					</div>
				</div>
				<hr>

				<div class="latex1">
					<img src="http://latex.codecogs.com/gif.latex?a^{2} + b^{2}  \geq 2ab"> => <img src="http://latex.codecogs.com/gif.latex?\frac{a^{2} + b^{2}}{2}  \geq ab">
				</div>
				<hr>

			</div><!-- /.container -->

			<script type='text/javascript' src="<?php echo $baseUrl ?>/dist/js/bootstrap.min.js"></script>
			<script type='text/javascript' src="<?php echo $baseUrl ?>/js/latex.js"></script>
			<!-- JavaScript jQuery code from Bootply.com editor -->
			<script type='text/javascript'>
				$(document).ready(function() {
					$(".tt").tooltip();
				});
			</script>

	</body>
</html>